:imagesdir: Images
:figure-caption: Рисунок
:table-caption: Таблица
:toc:
:toc-title: ОГЛАВЛЕНИЕ:
== Лабораторная работа 9



=== Задание:

* Измерить температуру микроконтроллера с помощью АЦП и инженекторных каналов.
* Значения температуры передать через UART и отобразить в программе Terminal.


=== 1. Настройка АЦП

Для преобразования сигнала, полученного со встроенного в микроконтроллер датчика температуры, в цифровой код используется АЦП.

*Аналого-цифровой преобразователь* (АЦП) – устройство, которое принимает аналоговые сигналы и генерирует соответствующие им цифровые сигналы, пригодные для дальнейшей обработки микропроцессором или другим цифровым устройством.

Для преобразования сигналов датчиков, где нужна высокая точность применяется _сигма-дельта АЦП_. Но в основном микроконтроллеры содержат в себе АЦП _последовательного приближения_ (_SAR_).


[source,c]
----
 //Переключение на частоту ADC1

   RCC::APB2ENR::ADC1EN::Enable::Set();

   //Переключение на температурный сенсор

   ADC_Common::CCR::TSVREFE::Enable::Set();

   //Установка режима одиночного преобразования

   ADC1::CR1::RES::Bits12::Set();
   ADC1::CR2::CONT::SingleConversion::Set();
   ADC1::CR2::EOCS::SingleConversion::Set();

   // Установка частоты диспретизации в 84 цикла для 18 каналa

   ADC1::SMPR1::SMP18::Cycles84::Set();

   // Установка длины последовательного преобразования на 1

   ADC1::JSQR::JL::Conversion1::Set();

   // Установка первого преобразования на 18 канал

   ADC1::JSQR::JSQ4::Set(18);

  return 1;
}
}
----

Для настройки и работы модуля UART нужны всего несколько регистра

* USART_CR1/CR2/CR3 -  регистр настройки 1
* USART_DR -  регистр принятого символа (регистр данных)
* USART_BRR – регистр настройки скорости передачи
* USART_SR  - регистр состояния
